     SELECT  
		A.REFERENCE_NUMBER,
		A.EXPLANATION,
		A.AMOUNT,
		A.CURRENCY_CODE,
		P.NAME,

	a.CUSTOMER_NUMBER
	FROM CRC.DIFFERENCE A WITH (NOLOCK)
	LEFT JOIN CRC.DIFFERENCE_DETAIL D (NOLOCK) ON A.REFERENCE_NUMBER = D.REFERENCE_NUMBER
	LEFT JOIN CRC.DIFFERENCE_PARAMETER P (NOLOCK) ON D.DIFFERENCE_TYPE = P.ID

	where a.BEGINNING_DATE>'20230101'	  and d.DIFFERENCE_TYPE=4		  